const assetsRoot = './assets/images/';

const EntitySkins = {
    Base: assetsRoot + 'base.svg',
    BaseHit: assetsRoot + 'base-hit.svg',
    BrickWall: assetsRoot + 'brick-wall.svg',
    SteelWall: assetsRoot + 'steel-wall.png',
    TankFirst: assetsRoot + 'tank.svg',
    TankSecond: assetsRoot + 'tank_2.svg',
    Shell: assetsRoot + 'shell.svg',
    hit1: assetsRoot + 'hit1.svg',
    hit2: assetsRoot + 'hit2.svg',
    hit3: assetsRoot + 'hit3.svg',
    village_house1: assetsRoot + 'village_house_1.svg',
    village_house2_A: assetsRoot + 'village_house_2_A.svg',
    village_house2_B: assetsRoot + 'village_house_2_B.svg',
    village_house3_A: assetsRoot + 'village_house_3_A.svg',
    village_house3_B: assetsRoot + 'village_house_3_B.svg',
    village_house4_A: assetsRoot + 'village_house_4_A.svg',
    village_house4_B: assetsRoot + 'village_house_4_B.svg',
    city_house1: assetsRoot + 'city_house_1.svg',
    city_house2_A: assetsRoot + 'city_house_2_A.svg',
    city_house2_B: assetsRoot + 'city_house_2_B.svg',
    city_house3_A: assetsRoot + 'city_house_3_A.svg',
    city_house3_B: assetsRoot + 'city_house_3_B.svg',
    city_house4_A: assetsRoot + 'city_house_4_A.svg',
    city_house4_B: assetsRoot + 'city_house_4_B.svg',
    water1: assetsRoot + 'water1.png',
    water2: assetsRoot + 'water2.png',
    foilageGreen: assetsRoot + 'bush_green.svg',
    foilageYellow: assetsRoot + 'bush_yellow.svg',
    treeOak: assetsRoot + 'oak_tree.svg',
    treeApple: assetsRoot + 'apple_tree.svg',
    bridgeUp: assetsRoot + 'bridge.png',
    bridgeLeft: assetsRoot + 'bridge_turned.png',
};

export default EntitySkins;
